platform :ios, ‘9.0’

target ‘BasicFramework’ do

  pod 'MBProgressHUD',
  pod 'AFNetworking'
  pod 'SDWebImage'
  pod 'Reachability'
  pod 'SBJson',
  pod 'JSONModel'
  pod 'Masonry'
  pod 'MyUUID'
  pod 'MYBlurIntroductionView'


end
